name: flutternew
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
 

  flutter:
    sdk: flutter
  postgres: ^2.6.1
  freezed_annotation: 2.4.4
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  


   
  flutter_localizations:
    sdk: flutter
    
database:
  host: 127.0.0.1
  port: 5432
  username: mi_usuario
  password: mi_contrasena
  databaseName: mi_base_de_datos

dev_dependencies:
  freezed: ^2.5.8
  

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
